---
- name: Upgrade RHEL7 to RHEL8
  hosts: node4.example.com
  strategy: free
  become: true
  force_handlers: true
  tasks:
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
...
