---
- name: Analysis
  hosts: node4.example.com
  vars:
    ANSIBLE_ROLES_PATH: "/root/.ansible/collections/ansible_collections/infra/leapp"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  tasks:
    - name: Generate preupgrade analysis report
      ansible.builtin.import_role:
        name: infra.leapp.analysis
...
